### Task 2: Sorting Practice 
1. Sort salary ascending 
2. Sort salary descending 
3. Sort by multiple columns

In [1]:
import pandas as pd
#create dataset
data ={"Name":["Arunima","Akhil","Deepika","Dona","Evon","Sagar","Meera","Hari","Sathya","Anagha"],
        "Salary":[20000,60000,40000,30000,45000,35000,15000,80000,55000,35000],
        "Department":["HR","AI","QA","DBA","AI","DBA","HR","AI","DBA","QA"],
        "Category":["a","c","b","c","b","b","b","a","a","b"],
        "City":["Trivandrum","Kochi","Bangalore","Calicut","Trivandrum","Kochi","Bangalore","Kochi","Calicut","Trivandrum"]}
df = pd.DataFrame(data)
df

      Name  Salary Department Category        City
0  Arunima   20000         HR        a  Trivandrum
1    Akhil   60000         AI        c       Kochi
2  Deepika   40000         QA        b   Bangalore
3     Dona   30000        DBA        c     Calicut
4     Evon   45000         AI        b  Trivandrum
5    Sagar   35000        DBA        b       Kochi
6    Meera   15000         HR        b   Bangalore
7     Hari   80000         AI        a       Kochi
8   Sathya   55000        DBA        a     Calicut
9   Anagha   35000         QA        b  Trivandrum

In [2]:
#sort salary ascending
df.sort_values("Salary")

      Name  Salary Department Category        City
6    Meera   15000         HR        b   Bangalore
0  Arunima   20000         HR        a  Trivandrum
3     Dona   30000        DBA        c     Calicut
5    Sagar   35000        DBA        b       Kochi
9   Anagha   35000         QA        b  Trivandrum
2  Deepika   40000         QA        b   Bangalore
4     Evon   45000         AI        b  Trivandrum
8   Sathya   55000        DBA        a     Calicut
1    Akhil   60000         AI        c       Kochi
7     Hari   80000         AI        a       Kochi

In [3]:
#sort salary descending
df.sort_values("Salary",ascending=False)

      Name  Salary Department Category        City
7     Hari   80000         AI        a       Kochi
1    Akhil   60000         AI        c       Kochi
8   Sathya   55000        DBA        a     Calicut
4     Evon   45000         AI        b  Trivandrum
2  Deepika   40000         QA        b   Bangalore
9   Anagha   35000         QA        b  Trivandrum
5    Sagar   35000        DBA        b       Kochi
3     Dona   30000        DBA        c     Calicut
0  Arunima   20000         HR        a  Trivandrum
6    Meera   15000         HR        b   Bangalore

In [4]:
#sort by multiple columns
df.sort_values(["Department","Salary"],ascending=[True,True])

      Name  Salary Department Category        City
4     Evon   45000         AI        b  Trivandrum
1    Akhil   60000         AI        c       Kochi
7     Hari   80000         AI        a       Kochi
3     Dona   30000        DBA        c     Calicut
5    Sagar   35000        DBA        b       Kochi
8   Sathya   55000        DBA        a     Calicut
6    Meera   15000         HR        b   Bangalore
0  Arunima   20000         HR        a  Trivandrum
9   Anagha   35000         QA        b  Trivandrum
2  Deepika   40000         QA        b   Bangalore

### Task 3: Grouping Practice 
1. Group by department 
2. Group by city 
3. Group by category

In [5]:
df.groupby("Department")

In [6]:
df.groupby("Department").size()

Department
AI     3
DBA    3
HR     2
QA     2
dtype: int64

In [7]:
df.groupby("City").size()

City
Bangalore     2
Calicut       2
Kochi         3
Trivandrum    3
dtype: int64

In [8]:
df.groupby("Category").size()

Category
a    3
b    5
c    2
dtype: int64

### Task 4: Aggregation Practice 
1. Find average salary 
2. Find total salary 
3. Count employees

In [9]:
# average salary
print(df["Salary"].mean())

41500.0

In [10]:
#average salary by department
df.groupby("Department")["Salary"].mean()

Department
AI     61666.666667
DBA    40000.000000
HR     17500.000000
QA     37500.000000
Name: Salary, dtype: float64

In [11]:
# total salary
print("Total Salary:", df["Salary"].sum())

Total Salary: 415000

In [12]:
#total salary by department
df.groupby("Department")["Salary"].sum()

Department
AI     185000
DBA    120000
HR      35000
QA      75000
Name: Salary, dtype: int64

In [13]:
#count employees 
print(df["Name"].count())

10

In [14]:
#employees per department
df.groupby("Department")["Name"].count()

Department
AI     3
DBA    3
HR     2
QA     2
Name: Name, dtype: int64

### Task 5: Multiple Aggregation 
1. Find mean 
2. Find max 
3. Find min

In [15]:
df["Salary"].agg(["mean","max","min"])

mean    41500.0
max     80000.0
min     15000.0
Name: Salary, dtype: float64

In [16]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

                    mean    max    min
Department
AI          61666.666667  80000  45000
DBA         40000.000000  55000  30000
HR          17500.000000  20000  15000
QA          37500.000000  40000  35000

### Task 6: Value Counts 
1. Count departments 
2. Count repeated values 
3. Analyze category frequency

In [17]:
#count departments
print(df["Department"].value_counts())

Department
AI     3
DBA    3
HR     2
QA     2
Name: count, dtype: int64

In [18]:
#count repeated values
df["City"].value_counts()

City
Trivandrum    3
Kochi         3
Bangalore     2
Calicut       2
Name: count, dtype: int64

In [19]:
#analyze category frequency
df["Category"].value_counts(normalize=True)

Category
b    0.5
a    0.3
c    0.2
Name: proportion, dtype: float64