### Task 2: Missing Data Practice 
1. Create dataset with missing values 
2. Detect missing values 
3. Count missing values

In [1]:
import pandas as pd
import numpy as np
data = {"Name":["Amritha","Athira","Athul","Dhanush","Evon","Geethu","Gokul","Hari","Irin","Jancy"],
        "Marks":[167,180,175,190,np.nan,166,172,159,182,np.nan],
        "City":["Eranakulam","Trivandrum","Idukki",None,"Kollam","Wayanad","Calicut",None,"Kannur","Malappuram"]}
df = pd.DataFrame(data)
df_1 = df.copy()

In [2]:
df.isnull()

    Name  Marks   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False   True
4  False   True  False
5  False  False  False
6  False  False  False
7  False  False   True
8  False  False  False
9  False   True  False

In [3]:
df.isnull().sum()

Name     0
Marks    2
City     2
dtype: int64

### Task 3: Remove Missing Data 
1. Drop rows with missing values 
2. Drop columns with missing values

In [4]:
#drop rows with missing values
df.dropna()

      Name  Marks        City
0  Amritha  167.0  Eranakulam
1   Athira  180.0  Trivandrum
2    Athul  175.0      Idukki
5   Geethu  166.0     Wayanad
6    Gokul  172.0     Calicut
8     Irin  182.0      Kannur

In [5]:
#drop columns with missing values
df.dropna(axis=1)

      Name
0  Amritha
1   Athira
2    Athul
3  Dhanush
4     Evon
5   Geethu
6    Gokul
7     Hari
8     Irin
9    Jancy

In [6]:
df.dropna(inplace=True)
df.isna().sum()

Name     0
Marks    0
City     0
dtype: int64

### Task 4: Fill Missing Data 
1. Fill with text 
2. Fill with mean value 
3. Fill numeric columns

In [8]:
#fill with text
df_1["City"] = df_1["City"].fillna("Unknown")

In [9]:
#fill with mean value
df_1["Marks"] = df_1["Marks"].fillna(df_1["Marks"].mean()).round(2)

In [10]:
df_1

      Name   Marks        City
0  Amritha  167.00  Eranakulam
1   Athira  180.00  Trivandrum
2    Athul  175.00      Idukki
3  Dhanush  190.00     Unknown
4     Evon  173.88      Kollam
5   Geethu  166.00     Wayanad
6    Gokul  172.00     Calicut
7     Hari  159.00     Unknown
8     Irin  182.00      Kannur
9    Jancy  173.88  Malappuram

In [11]:
#Fill numeric columns
numeric_cols = df_1.select_dtypes(include="number").columns
df_1[numeric_cols] = df_1[numeric_cols].fillna(df_1[numeric_cols].mean())

### Task 5: Duplicate Handling 
1. Create duplicate rows 
2. Detect duplicates 
3. Remove duplicates

In [13]:
#create duplicate rows
df_dup =pd.concat([df_1,df_1.iloc[:2]],ignore_index =True)
df_dup

       Name   Marks        City
0   Amritha  167.00  Eranakulam
1    Athira  180.00  Trivandrum
2     Athul  175.00      Idukki
3   Dhanush  190.00     Unknown
4      Evon  173.88      Kollam
5    Geethu  166.00     Wayanad
6     Gokul  172.00     Calicut
7      Hari  159.00     Unknown
8      Irin  182.00      Kannur
9     Jancy  173.88  Malappuram
10  Amritha  167.00  Eranakulam
11   Athira  180.00  Trivandrum

In [16]:
#detect duplicates
df_dup.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
dtype: bool

In [17]:
df_dup[df_dup.duplicated()]

       Name  Marks        City
10  Amritha  167.0  Eranakulam
11   Athira  180.0  Trivandrum

In [ ]:
#remove duplicates
df_clean=df_dup.drop_duplicates()
df_clean

      Name   Marks        City
0  Amritha  167.00  Eranakulam
1   Athira  180.00  Trivandrum
2    Athul  175.00      Idukki
3  Dhanush  190.00     Unknown
4     Evon  173.88      Kollam
5   Geethu  166.00     Wayanad
6    Gokul  172.00     Calicut
7     Hari  159.00     Unknown
8     Irin  182.00      Kannur
9    Jancy  173.88  Malappuram

## Task 6: Column Operations 
1. Rename columns 
2. Change data type 
3. Print data types

In [20]:
#rename columns
df_1.rename(columns={"Marks":"Score","City":"Location"}, inplace=True)
df_1

      Name   Score    Location
0  Amritha  167.00  Eranakulam
1   Athira  180.00  Trivandrum
2    Athul  175.00      Idukki
3  Dhanush  190.00     Unknown
4     Evon  173.88      Kollam
5   Geethu  166.00     Wayanad
6    Gokul  172.00     Calicut
7     Hari  159.00     Unknown
8     Irin  182.00      Kannur
9    Jancy  173.88  Malappuram

In [22]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      10 non-null     object
 1   Score     10 non-null     float64
 2   Location  10 non-null     object
dtypes: float64(1), object(2)
memory usage: 372.0+ bytes

In [ ]:
#change data type
df_1["Score"] = df_1["Score"].round().astype(int)
#print data types
df_1.dtypes

Name        object
Score        int64
Location    object
dtype: object