### Task 2: Series Practice 
1. Create Series 
2. Create Series with custom index 
3. Access Series values

In [1]:
import pandas as pd
#create series
a = pd.Series([10,30,50,70,90])
print(a)

0    10
1    30
2    50
3    70
4    90
dtype: int64

In [3]:
#create series with custom index
marks = pd.Series([59,78,67,80], index=["Maths", "Science", "Biology", "English"])
print (marks)
# access series values
marks["English"]

Maths      59
Science    78
Biology    67
English    80
dtype: int64

80

### Task 3: DataFrame Practice 
1. Create DataFrame using dictionary 
2. Print DataFrame 
3. Add one more column

In [25]:
students = {"Name":["Aparna","Arjun","Megha","Meenu","Mithun","Neethu","Prince","Sourav"],
            "Marks":[67,72,56,60,89,59,73,80]}
df = pd.DataFrame(students)
print(df)
#add new column 
df["Grade"] = ["B","B+","C","C+","A","C","B+","A"]
print("Students df:\n",df)

     Name  Marks
0  Aparna     67
1   Arjun     72
2   Megha     56
3   Meenu     60
4  Mithun     89
5  Neethu     59
6  Prince     73
7  Sourav     80
Students df:
      Name  Marks Grade
0  Aparna     67     B
1   Arjun     72    B+
2   Megha     56     C
3   Meenu     60    C+
4  Mithun     89     A
5  Neethu     59     C
6  Prince     73    B+
7  Sourav     80     A

### Task 4: Data Access 
1. Access single column 
2. Access multiple columns 
3. Print specific rows

In [ ]:
#access single column
df["Name"]

0    Aparna
1     Arjun
2     Megha
3     Meenu
4    Mithun
5    Neethu
6    Prince
7    Sourav
Name: Name, dtype: object

In [ ]:
#access multiple columns
df[["Name","Marks"]]

     Name  Marks
0  Aparna     67
1   Arjun     72
2   Megha     56
3   Meenu     60
4  Mithun     89
5  Neethu     59
6  Prince     73
7  Sourav     80

In [ ]:
# access specific rows
print(df.loc[0])

Name     Aparna
Marks        67
Grade         B
Name: 0, dtype: object

In [29]:
print(df.loc[3])

Name     Meenu
Marks       60
Grade       C+
Name: 3, dtype: object

In [ ]:
#access specfic range of rows
print(df.iloc[3:5])

     Name  Marks Grade
3   Meenu     60    C+
4  Mithun     89     A

In [32]:
print(df.loc[3:5])

     Name  Marks Grade
3   Meenu     60    C+
4  Mithun     89     A
5  Neethu     59     C

### Task 5: Data Information 
1. Use head() 
2. Use tail() 
3. Use info()

In [33]:
df.head()

     Name  Marks Grade
0  Aparna     67     B
1   Arjun     72    B+
2   Megha     56     C
3   Meenu     60    C+
4  Mithun     89     A

In [ ]:
df.head(2)

     Name  Marks Grade
0  Aparna     67     B
1   Arjun     72    B+
2   Megha     56     C

In [34]:
df.tail()

     Name  Marks Grade
3   Meenu     60    C+
4  Mithun     89     A
5  Neethu     59     C
6  Prince     73    B+
7  Sourav     80     A

In [35]:
df.tail(2)

     Name  Marks Grade
6  Prince     73    B+
7  Sourav     80     A