### Task 2: CSV Practice 
1. Create CSV file 
2. Read CSV using Pandas 
3. Print dataset

In [4]:
import pandas as pd
data ={"Name":["Akhil","Ann Lin","Athira","Hari","Heera","Meera","Mithun","Neenu","Pratheesh","Sameera"],
        "Marks":[45,56,78,62,59,66,77,82,85,90],
        "City":["Calicut","Trivandrum","Idukki","Wayanad","Kannur","Palakkad","Kollam","calicut","Trivandrum","Wayanad"]}
df = pd.DataFrame(data)
df.to_csv("students.csv", index=False)
df_1 = pd.read_csv("students.csv")
df_1.head()

      Name  Marks        City
0    Akhil     45     Calicut
1  Ann Lin     56  Trivandrum
2   Athira     78      Idukki
3     Hari     62     Wayanad
4    Heera     59      Kannur

### Task 3: Column Selection 
1. Select single column 
2. Select multiple columns 
3. Print specific column values

In [5]:
#select single column
df_1["Name"]

0        Akhil
1      Ann Lin
2       Athira
3         Hari
4        Heera
5        Meera
6       Mithun
7        Neenu
8    Pratheesh
9      Sameera
Name: Name, dtype: object

In [6]:
#select multiple columns
df[["Name","Marks"]]

        Name  Marks
0      Akhil     45
1    Ann Lin     56
2     Athira     78
3       Hari     62
4      Heera     59
5      Meera     66
6     Mithun     77
7      Neenu     82
8  Pratheesh     85
9    Sameera     90

In [ ]:
#print specific column values
df["Marks"].values

array([45, 56, 78, 62, 59, 66, 77, 82, 85, 90], dtype=int64)

### Task 4: Row Selection 
1. Select row using loc 
2. Select row using iloc 
3. Slice rows

In [ ]:
#select row using loc
df.loc[0]

Name       Akhil
Marks         45
City     Calicut
Name: 0, dtype: object

In [ ]:
#select row using iloc
df.iloc[1]

Name        Ann Lin
Marks            56
City     Trivandrum
Name: 1, dtype: object

In [14]:
#slice rows
df.iloc[0:6]

      Name  Marks        City
0    Akhil     45     Calicut
1  Ann Lin     56  Trivandrum
2   Athira     78      Idukki
3     Hari     62     Wayanad
4    Heera     59      Kannur
5    Meera     66    Palakkad

### Task 5: Filtering 
1. Filter marks > 80 
2. Filter city names 
3. Combine conditions

In [ ]:
#Filter marks>80
df[df["Marks"]>80]

        Name  Marks        City
7      Neenu     82     calicut
8  Pratheesh     85  Trivandrum
9    Sameera     90     Wayanad

In [ ]:
#Filter city names
df[df["City"]=="Trivandrum"]

        Name  Marks        City
1    Ann Lin     56  Trivandrum
8  Pratheesh     85  Trivandrum

In [ ]:
#combine conditions
df[(df["Marks"]>80) &(df["City"]=="Trivandrum")]

        Name  Marks        City
8  Pratheesh     85  Trivandrum